---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongo
type: Opaque
data:
  mongo-root-username: cm9vdA==
#  root
  mongo-root-password: cGFzc3dvcmQ=
#  password
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
  namespace: mongo
type: Opaque
data:
  mongo-root-username: cm9vdA==
  mongo-root-password: cGFzc3dvcmQ=
---