---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-go
  labels:
    app.kubernetes.io/instance: hello-go
    app.kubernetes.io/name: hello-go
    name: hello-go
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
  namespace: hello-go
  labels:
    app: hello-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
        - name: hello-go
          imagePullPolicy: IfNotPresent
          image: hello-go
---
apiVersion: v1
kind: Service
metadata:
  name: hello-go-service
  namespace: hello-go
spec:
  selector:
    app: hello-go
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8180
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-go-ingress
  namespace: hello-go
spec:
  ingressClassName: nginx
  rules:
    - host: hello-go.here
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-go-service
                port:
                  number: 8888
---
